default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 181023
  host: 127.0.0.1
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chat_api_development

test:
  <<: *default
  database: chat_api_test



production:
  primary:
    <<: *default
    database: chat_api_production
  cache:
    <<: *default
    database: chat_app
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: chat_app
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: chat_app
    migrations_paths: db/cable_migrate
